# Dataset
ds_rate: 2
dataset_name: 'lara'
train_vids_file: '/path/to/your/train.split1.bundle'
test_vids_file: '/path/to/your/test.split1.bundle'
channel: 6
num_classes: 8
gt_path: '/path/to/your/lara/groundTruth_/'
feature_path: '/path/to/your/lara/features7/'
joint_num: 19
feature_type: 'origin'

# hyper
learning_rate: 0.0005
period_epoch: 2
num_epochs: 200
batch_size: 4
lr: 0.0005

# Spatial
feat_dim: 8
spatial_dil: [1,2,4,8,16,32,64,128,256,512]
graph_layout: 'lara'
graph_strategy: 'spatial'
spatial_filters: 64
edge_importance_weighting: True

# Temporal
num_stages: 4
num_f_maps: 64
num_layers: 10
temporal_dil: [1,2,4,8,16,32,64,128,256,512]


# tensorboard
boardOn: False
port: 10006

#seed
seed: 199656


