# Dataset
ds_rate: 1
dataset_name: 'tug'
train_vids_file: '/path/to/your/train.split1.bundle'
test_vids_file: '/path/to/your/test.split1.bundle'
channel: 6
num_classes: 6
gt_path: '/path/to/your/tug/groundTruth_/'
feature_path: '/path/to/your/tug/features7/'âˆ‚
joint_num: 19
feature_type: 'new'
sample_rate: 2

# hyper
learning_rate: 0.0005
warmup: True
warm_epoch: 10
period_epoch: 2
num_epochs: 300
batch_size: 5
lr: 0.0005


# action segmentation loss weight
cls_loss_weight: 1

# SASNet
spatial: 'stgcn'
temporal: 'mstcn'

# Spatial
feat_dim: 64
spatial_dil: [1,2,4,8,16,32,64,128,256,512]
graph_layout: 'lara'
graph_strategy: 'spatial'
spatial_filters: 64
edge_importance_weighting: True

# Temporal
num_stages: 4
num_f_maps: 64
num_layers: 10
temporal_dil: [1,2,4,8,16,32,64,128,256,512]

# tensorboard
boardOn: False
port: 10006
tsneepoch: 111


#seed
seed: 199656

# logger
is_board_on: True
is_txt_on: True
is_print_on: True

boundary_th: 0.5
ce: true
ce_weight: 1.0
class_weight: true
csv_dir: ./csv
dampening: 0.0
dataset_dir: ./dataset
focal: false
focal_weight: 1.0
gstmse: true
gstmse_index: feature
gstmse_weight: 1.0
in_channel: 2048
iou_thresholds:
- 0.1
- 0.25
- 0.5
lambda_b: 0.1
max_epoch: 100
model: ActionSegmentRefinementNetwork
momentum: 0.9
n_features: 64
n_layers: 10
n_stages: 4
n_stages_asb: 4
n_stages_brb: 4
nesterov: true
num_workers: 4
optimizer: Adam
param_search: false
split: 1
tmse: false
tmse_weight: 0.15
tolerance: 5
weight_decay: 0.0001

